
default_language_version:
        python: python3

repos:

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
      - id: mdformat
        name: mdformat
        entry: mdformat .
        language_version: python3


  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln

  - repo: https://github.com/isidentical/teyit
    rev: 0.4.3
    hooks:
      - id: teyit
